### PR TITLE
Compiletest docs for recently-added features

### PR DESCRIPTION
**Pull request by Zalathar**
- https://github.com/rust-lang/rust/pull/126257
- https://github.com/rust-lang/rust/pull/126111
- https://github.com/rust-lang/rust/pull/126008

### CODE REVIEW

**Comment by Zalathar** [comment]
cc @jieyouxu

**Comment by jieyouxu** [comment]
Looks good, let's merge it after the needs-* directive rename PR is merged

**Comment by Zalathar** [comment]
Also added docs for header substitutions `{{sysroot-base}}` and `{{target-linker}}`.

**Review by jieyouxu — APPROVED** [review]
Thanks for the update!

**Review by jieyouxu — APPROVED** [review]
👍

**Pull request merged**
