### PR TITLE
building: Update instructions for ./x setup editor

### PR DESCRIPTION
**Pull request by mrkajetanp**
Update the guide as suggested. I reformatted the quickstart file and made a couple of smaller fixes too.
r? @Kobzol

### CODE REVIEW

**Review by Kobzol — APPROVED** [review]
Great, thank you! :)

**Comment by Kobzol** [comment]
You'll need to rebase over https://github.com/rust-lang/rustc-dev-guide/pull/2087 (please keep the links at the end of the document that you have added, and remove the inline links).

**Comment by mrkajetanp** [comment]
Np, I moved the git hook link to the bottom too while I was at it

**Review by Kobzol — APPROVED** [review]
Great, thank you!

**Pull request merged**
