### PR TITLE
clarify subtree tool policy

### PR DESCRIPTION
**Pull request by RalfJung**
Cc https://github.com/rust-lang/rust/issues/104962

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks good!

**Review by flip1995 — APPROVED** [review]
This policy sounds good to me. So :+1: from the Clippy side.

**Review by calebcartwright — APPROVED** [review]
Agreed. :+1: on this from rustfmt perspective

**Comment by camelid** [comment]
It looks like this is ready to merge. Is that correct, or are we waiting on approval from another team?

**Comment by JohnTitor** [comment]
I also think this is ready to merge as it has some approvals from some subtree maintainers. Let's merge, and follow-up if there are any concerns/comments.

**Pull request merged**
