### PR TITLE
Add guide for rustdoc search implementation

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It's a really great improvement, thanks! Now let's see if bors works on this repository...

@bors r+

**Comment by GuillaumeGomez** [comment]
Doesn't seem so. Oh well.

cc @tshepang :)

**Review by fmease — APPROVED** [review]

**Comment by fmease** [comment]
There you go ;)

**Comment by GuillaumeGomez** [comment]
:o You have the poweeeeeer. That's convenient, thanks! :laughing:

**Comment by tshepang** [comment]
all compiler and libs people can merge

**Pull request merged**
