### PR TITLE
Try to avoid confusion in `how-to-build-and-run.md`

### PR DESCRIPTION
**Pull request by sslime336**
This pr is the follower of #1710, which didn't finish it's job perfectly.

### CODE REVIEW

**Comment by jyn514** [comment]
@sslime336 this needs to be rebased over master - see https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing for instructions. You'll want to drop all except the last commit ("Try to avoid confusion").

**Comment by sslime336** [comment]
yes, I'm sorry I did not handle this well. I will handle this sooner.

**Comment by sslime336** [comment]
Okey, here's new pr #1713 (hope this time it could be allright :P )
Sorry for making the workflow so messy.

**Comment by jyn514** [comment]
that's ok! thank you for fixing it :)

**Pull request closed without merging**
