### PR TITLE
Add a paragraph on installing `ninja-build` in order to build LLVM

### PR DESCRIPTION
**Pull request by daira**
refs https://github.com/rust-lang/rust/issues/89091

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by the8472** [comment]
ninja is already listed in the [prerequisites](https://rustc-dev-guide.rust-lang.org/building/prerequisites.html). And there it lists either gnu make *or* ninja. Links to install instructions should probably go there.

**Comment by daira** [comment]
Hmm. It says "ninja, or GNU make 3.81 or later", and I have GNU make, which is not sufficient by default.

**Comment by jyn514** [comment]
@daira GNU make would have worked if you had ninja = false in config.toml. We shouldn't remove those docs.

**Comment by jyn514** [comment]
I'm going to close this for now - I think improving errors from x.py is better than making the guide even longer, and it's not clear to me that this would be easy to find if you're building for the first time.

**Pull request closed without merging**
