### PR TITLE
Opt into, rather than out of, linkcheck

### LINKED ISSUE #2178: Can't run `mdbook build` locally without installing or disabling linkcheck
As of #2103:

```text
$ mdbook build --open
2024-12-30 11:30:43 [INFO] (mdbook::book): Book building has started
2024-12-30 11:30:43 [INFO] (mdbook::book): Running the html backend
2024-12-30 11:30:44 [INFO] (mdbook::book): Running the linkcheck backend
2024-12-30 11:30:44 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
Checking files changed in master...: 
exec mdbook-linkcheck2 -f 
/Users/stuart/Dev/rust/dev-guide/ci/linkcheck.sh: line 47: exec: mdbook-linkcheck2: not found
2024-12-30 11:30:44 [WARN] (mdbook::renderer): Error writing the RenderContext to the backend, Broken pipe (os error 32)
2024-12-30 11:30:44 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2024-12-30 11:30:44 [ERROR] (mdbook::utils): Error: Rendering failed
2024-12-30 11:30:44 [ERROR] (mdbook::utils): 	Caused By: The "linkcheck" renderer failed
```

---

Building the book now fails if `mdbook-linkcheck2` has not been manually installed, even if the contributor doesn't care about linkcheck and just wants to build the book to preview their changes.

And while there is a workaround available, it isn't mentioned by the error message at all.

---

As a temporary workaround, this works:

```
$ SKIP_LINKCHECK=1 mdbook build
```

### PR DESCRIPTION
**Pull request by camelid**
Fixes #2178.

This makes it less of a hassle to render the book locally.

### CODE REVIEW

**Comment by marxin** [comment]
Thanks for caring about the reported issue. Just wanted to mention that with the suggested change, if a link is broken, then people will be surprised that the local build is fine, but the CI will complain.

What about rather doing detection of the binary `mdbook-linkcheck2`, if it exists, then the link validation is run. If not, a warning will be displayed and the link checking will be skipped?

**Comment by jieyouxu** [comment]
I'm fine with doing binary detection (maybe in a follow-up?), but let's merge this first to unblock local builds.

**Comment by jieyouxu** [comment]
Thanks!

**Comment by marxin** [comment]
> I'm fine with doing binary detection (maybe in a follow-up?), but let's merge this first to unblock local builds.

Sure, done in #2181.

**Pull request merged**
