### PR TITLE
turn off caching for normal CI runs

### PR DESCRIPTION
**Pull request by mark-i-m**
Trying again!

### CODE REVIEW

**Comment by mark-i-m** [comment]
cc @camelid @jyn514 I'm not sure why CI isn't running a build. Any ideas?

**Comment by camelid** [comment]
Did we run out of build credits? Cc #940.

**Comment by mark-i-m** [comment]
Or else travis just doesn't like me...

**Comment by mark-i-m** [comment]
I'm just going to go ahead and close this. Perhaps a cleaner solution would be to add a "--no-caching" flag to mdbook for CI runs.

**Comment by camelid** [comment]
Yeah, it's weird how Travis didn't work....

**Pull request closed without merging**
