### PR TITLE
Tweak wording around provider purity

### LINKED ISSUE #825: Explaining what is pure function in the context?
The [Caching/Memoization](https://rustc-dev-guide.rust-lang.org/queries/query-evaluation-model-in-detail.html#cachingmemoization) section talks about pure functions.
Can we link to pure function definition?

### PR DESCRIPTION
**Pull request by camelid**
Cc #825 (doesn't fix though).

### CODE REVIEW

**Comment by jyn514** [comment]
@camelid these seem like good changes, but I'm not sure this should close https://github.com/rust-lang/rustc-dev-guide/issues/825.https://github.com/rust-lang/rustc-dev-guide/issues/825#issuecomment-674466651

**Comment by camelid** [comment]
Yeah, I'm not exactly sure what the issue is asking for. I guess we need to clarify whether providers are allowed to perform I/O? I'm guessing no, but I don't know.

**Comment by camelid** [comment]
I'll change this so it doesn't close the issue.

**Comment by jyn514** [comment]
@lzutao I think it's unlikely anyone will know what changes you wanted other than you. Are you interested in making a PR with the information you were talking about?

**Comment by camelid** [comment]
@jyn514 In the meantime, should we merge this since it clarifies the wording slightly and fixes a typo?

**Review by jyn514 — APPROVED** [review]

**Pull request merged**
