### PR TITLE
Update some bibliography links

### PR DESCRIPTION
**Pull request by camelid**

### CODE REVIEW

**Comment by camelid** [comment]
(CI is failing because #908 hasn't been merged yet.)

**Comment by camelid** [comment]
Ok, #908 was merged so rebasing.

**Comment by camelid** [comment]
Squashed and rebased.

**Review by LeSeulArtichaut — APPROVED** [review]
Did you go through every link to find out which links you could update? ❤️

**Comment by camelid** [comment]
> Did you go through every link to find out which links you could update? ❤️

Yes; it took much longer than I thought :)

But hopefully we won't have to update them again for a while!

**Pull request merged**
