### PR TITLE
update const stability docs

### PR DESCRIPTION
**Pull request by RalfJung**
This updates the docs for https://github.com/rust-lang/rust/pull/131349. Should only land once that PR landed.

### CODE REVIEW

**Comment by RalfJung** [comment]
@rust-lang/libs @rust-lang/libs-api FYI, and also would be good to get some feedback if you think this system makes sense or you would like to see some aspect of it work differently. :)

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/131349 is merged now, so could someone merge this docs PR as well? :)

**Comment by RalfJung** [comment]
Seems like this was merged with a rebase, not a clean merge? That makes it a lot harder to automatically track which of my branches have been merged already... :(

**Comment by jieyouxu** [comment]
I think I just clicked one of the merge buttons, I'll talk with other dev-guide maintainers and see we can stick with *one* of the merging options, lol.

**Comment by jieyouxu** [comment]
> Seems like this was merged with a rebase, not a clean merge? That makes it a lot harder to automatically track which of my branches have been merged already... :(

@RalfJung actually just to clarify, would a rebase and merge work? I may have accidentally clicked the squash and merge.

**Comment by RalfJung** [comment]
Rebase and merge still means the commit as it exists in my branch does not end up in the repo, leaving me with no way to automatically determine that my branch was merged. So I have to delete all the old branches by hand, which is somewhat tedious. Lucky enough most rust-lang repos use a normal merge so I can have some scripts that detect all branches which have been merged (local and remote) and delete them. :)

I understand some people prefer a linear history, but I don't quite understand why... and in rust-lang we don't seem to have a default policy either way.

**Comment by jieyouxu** [comment]
Right. So apparently in this repo the default "merge" button is disabled for some reason, I'll ask around why... This is just docs so I really don't think the rust-lang/rust no merge policy is relevant.

**Comment by RalfJung** [comment]
rust-lang uses merge commits without rebase to merge PRs. The policy there is only about no merge commits *inside* a PR.

**Pull request merged**
