### PR TITLE
Hir map

### PR DESCRIPTION
**Pull request by spastorino**
I believe what's right now in the guide is outdated.

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]

**Comment by jyn514** [comment]
The CI failure is weird:

```
$ mdbook build
2020-09-25 20:06:39 [ERROR] (mdbook::utils): Error: Summary parsing failed
2020-09-25 20:06:39 [ERROR] (mdbook::utils): 	Caused By: There was an error parsing the suffix chapters
2020-09-25 20:06:39 [ERROR] (mdbook::utils): 	Caused By: failed to parse SUMMARY.md line 165, column 1: Suffix chapters cannot be followed by a list
The command "mdbook build" exited with 101.
```

**Comment by LeSeulArtichaut** [comment]
I think I have not been able to re-run CI, which is weird. @jyn514 mind trying yourself? :)

**Comment by JohnTitor** [comment]
CI says:

```
$ git rebase origin/master
First, rewinding head to replay your work on top of it...
Applying: add `mdbook init`
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in src/SUMMARY.md
Auto-merging src/SUMMARY.md
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .gitignore
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 add `mdbook init`
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

Seems the branch is outdated and you should rebase manually.

**Comment by mark-i-m** [comment]
Rebased.

**Pull request merged**
