### PR TITLE
Check `BASE_SHA` only if it's a PR

### LINKED ISSUE #1082: New GHA CI seems to not work
From the build for 674f73da63e127b143adbb613197f5630d68105d:

```
2021-03-10 17:07:14 [INFO] (mdbook::book): Book building has started
2021-03-10 17:07:14 [INFO] (mdbook::book): Running the html backend
2021-03-10 17:07:16 [INFO] (mdbook::book): Running the linkcheck backend
2021-03-10 17:07:16 [INFO] (mdbook::renderer): Invoking the "linkcheck" renderer
2021-03-10 17:07:16 [WARN] (mdbook::renderer): Renderer command `../../ci/linkcheck.sh` uses a path relative to the renderer output directory `/home/runner/work/rustc-dev-guide/rustc-dev-guide/book/linkcheck`. This was previously accepted, but has been deprecated. Relative executable paths should be relative to the book root.
error: unexpected state: BASE_SHA must be non-empty in CI
2021-03-10 17:07:16 [WARN] (mdbook::renderer): Error writing the RenderContext to the backend, Broken pipe (os error 32)
Error: -10 17:07:16 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
Error: -10 17:07:16 [ERROR] (mdbook::utils): Error: Rendering failed
Error: -10 17:07:16 [ERROR] (mdbook::utils): 	Caused By: The "linkcheck" renderer failed
Error: Process completed with exit code 101.
```

cc @JohnTitor

### PR DESCRIPTION
**Pull request by JohnTitor**
Should fix #1082

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hm I'm not sure why "Page Build" is required, perhaps the branch protection is misconfigured?

**Comment by LeSeulArtichaut** [comment]
IMO we don't need CI requirements anyway, I think we should discuss it with the WG someday... 🤷‍♂️

**Comment by camelid** [comment]
Looks like Page Build status check is still pending. Might be worth asking T-infra to look into it.

**Comment by JohnTitor** [comment]
@Mark-Simulacrum could you take a look?

**Comment by Mark-Simulacrum** [comment]
Should be fixed now! Not sure what happened, I don't recall checking that box, but maybe I misclicked or something.

**Pull request merged**
