### PR TITLE
Clarify section on MIR construction

### PR DESCRIPTION
**Pull request by camelid**
Also cleaned up some other minor stuff.

I do not know much about how MIR works (that's why I was reading this section!), so I'm not 100% sure if this was the intended meaning. Maybe someone who knows more about MIR could check this?

### CODE REVIEW

**Comment by camelid** [comment]
@rust-lang/miri If you get a chance, could you take a quick look at this?

**Comment by camelid** [comment]
Darn, how can I ping the MIR/MIRI team?

**Comment by oli-obk** [comment]
r? @oli-obk 

there's the `wg-mir-opt` team, but I don't think you can ping it without being an organization member

**Comment by oli-obk** [comment]
@bors r+ rollup

Thanks, this is a clear improvement of the docs. Please don't hesitate to `r? @oli-obk` any PRs for MIR docs, no matter how small.

**Review by tshepang — APPROVED** [review]

**Comment by tshepang** [comment]
hehe, we don't bors in here @oli-obk

**Pull request merged**
