### PR TITLE
Rename `librustc` to `librustc_middle`

### LINKED ISSUE #640: Broken link to no-longer-extant `has_any_child_of`
[CI is failing on an unrelated part of my change](https://travis-ci.com/github/rust-lang/rustc-dev-guide/builds/156240115#L339), and it looks like the `has_any_child_of` query linked in https://github.com/rust-lang/rustc-dev-guide/blob/master/src/borrow_check/moves_and_initialization/move_paths.md#cross-references no longer exists. If it had just moved I could add a commit to my PR taking care of that but I'm not sure how to change this text to in order to reflect whatever changed to remove that query.

Halp?

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
This is a first draft of the changes. I wanted to use the CI to detect broken links as soon as the new nightly is pushed to `doc.rust-lang.org`.
- Replaced occurences of `librustc::` with `librustc_middle::` (code paths)
- Replaced occurences of `librustc/` with `librustc_middle/` (file paths)
- Replaced occurences of `/rustc/` with `/rustc_middle/` (doc paths)

cc rust-lang/rust#70536

EDIT (mark-i-m): I've rolled up all of the link fixing PRs into this one, since none of them can individually pass CI.

resolves #640 #641 #646

### CODE REVIEW

**Comment by mark-i-m** [comment]
It looks like the new rustdocs have not uploaded yet.

**Comment by mark-i-m** [comment]
I've rolled together the other link fixes too.

**Comment by mark-i-m** [comment]
cc @ecstatic-morse @anp @tshepang

**Comment by LeSeulArtichaut** [comment]
Docs are now uploaded https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/

**Comment by JohnTitor** [comment]
Re-triggered CI, seems some commit-specified links are broken.

**Comment by tshepang** [comment]
@LeSeulArtichaut just a few failures left, which are links to exact commits. I think those you are must just revert.

**Pull request merged**
