### PR TITLE
correct minor grammar mistake

### PR DESCRIPTION
**Pull request by JoshuaNitschke**
correct `a lots` to `a lot` on implementing_new_features.md

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
Thanks!

**Comment by jyn514** [comment]
Hmm, I don't see travis checks running: https://travis-ci.org/github/rust-lang/rustc-dev-guide/pull_requests

Maybe we've already run out of credits? https://github.com/rust-lang/rustc-dev-guide/issues/940 That was just a few days ago, though ...

**Comment by jyn514** [comment]
cc @spastorino

**Comment by JohnTitor** [comment]
Let's see if re-opening solves it...

**Comment by JohnTitor** [comment]
> 
> 
> Hmm, I don't see travis checks running: [travis-ci.org/github/rust-lang/rustc-dev-guide/pull_requests](https://travis-ci.org/github/rust-lang/rustc-dev-guide/pull_requests)

You should see travis-ci.com, not travis-ci.org btw.

**Pull request merged**
