### PR TITLE
Add reference PRs for `r?` and `r+` comments

### PR DESCRIPTION
**Pull request by JohnTitor**
I think this would also help new contributors understand how the comment works.

### CODE REVIEW

**Comment by JohnTitor** [comment]
I'd like to add some more changes, one sec.

**Comment by JohnTitor** [comment]
Add a reference for `r+` as well, it's ready to review :)

**Review by jyn514 — APPROVED** [review]
LGTM but you need to rebase over your other PR ;)

**Comment by JohnTitor** [comment]
Rebased!

**Pull request merged**
