### PR TITLE
Change ICE-breaker ping to use the new aliases

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
I'm not sure if this is really useful, but I think the "full" invocation is really long and not convenient to learn.

Related to rust-lang/rust#69949

### CODE REVIEW

**Comment by JohnTitor** [comment]
I believe it's reasonable to tell that we have aliases for simplicity. We have some aliases and they might be changed/added so I think it's better to add a note and point to the triagebot.toml on rust-lang/rust.

**Comment by LeSeulArtichaut** [comment]
@JohnTitor I wrote a note in 6e11e5b, but I'm not fully satisfied with the wording. Would you mind reviewing? Thanks 😄

**Comment by pnkfelix** [comment]
I think the thrust of @JohnTitor 's comment was that it would be best to provide the non-aliased versions first, since I suspect those will never change (it seems more likely we'd retire a given ICE-breaker group than rename it).

And then, after that, state that some aliases exist (with the link to the triagebot toml), that they are subject to change, and *then* give a second code block showing the invocations with the aliases.

Does that make sense?

**Comment by pnkfelix** [comment]
(One reason it could be good to include the non-aliased versions in these docs is that if someone writes some tools, e.g. something to assist with triage, then it would be good for those tools to probably use the non-aliased versions...)

**Comment by JohnTitor** [comment]
> I think the thrust of @JohnTitor 's comment was that it would be best to provide the non-aliased versions first, since I suspect those will never change (it seems more likely we'd retire a given ICE-breaker group than rename it).

Yeah, that's exactly what I mean :)

**Comment by mark-i-m** [comment]
Ping @LeSeulArtichaut  :)

**Pull request merged**
