### PR TITLE
Fixes typo in getting started guide

### PR DESCRIPTION
**Pull request by imdanielsp**
### Change

Fixes a small typo in the `getting-started.md` page.

### CODE REVIEW

**Comment by igaray** [comment]
Thanks!

**Review by igaray — APPROVED** [review]

**Comment by imdanielsp** [comment]
@igaray I don't have merge permissions, is that something that you could do?

**Comment by igaray** [comment]
I like to either merge or approve but not both, even for trivial matters. Someone will come along shortly I'm sure. :)

**Comment by jyn514** [comment]
> I like to either merge or approve but not both, even for trivial matters. Someone will come along shortly I'm sure. :)

Hmm, do you mind saying why?

**Comment by igaray** [comment]
As a habit to have more eyes on changes, for consensus and error catching, things might slip by me. I'd be ok with making an exception for typos.

**Pull request merged**
