### PR TITLE
Add back the `canonicalization` chapter.

### LINKED ISSUE #1527: "Canonical queries" section doesn't explain canonical queries
https://rustc-dev-guide.rust-lang.org/traits/canonical-queries.html doesn't mention the word "canonical" once. It looks like the docs got deleted in https://github.com/rust-lang/rustc-dev-guide/pull/679. @crlf0710 do you have time to add these back? Canonicalization is important and still happens in rustc, not chalk.

https://github.com/rust-lang/rust/blob/e940f845be13ff37d4ba28df5f40d74e5b0895a0/compiler/rustc_trait_selection/src/traits/mod.rs#L103-L114

### PR DESCRIPTION
**Pull request by crlf0710**
Fixes #1527

### CODE REVIEW

**Comment by spastorino** [comment]
cc @lcnr

**Review by jyn514 — COMMENTED** [review]
Thanks! This looks good but it seems strange to add it as a new page instead of replacing `canonical-queries` (which today doesn't talk about canonical queries at all). Also, putting it under "chalk-based trait solving" seems strange because it doesn't involve chalk at all. Maybe you can rename the current page to "trait queries" and move both to the higher "trait solving section"?

That said, `canonical-queries` today seems to have a lot of overlap with `lowering-to-logic` so maybe it makes sense to just remove it altogether? 🤔

**Comment by spastorino** [comment]
@lcnr thoughts about this?.

**Comment by lcnr** [comment]
I don't have an opinion here, it is probably useful to add this. there's some overlap with https://rustc-dev-guide.rust-lang.org/solve/canonicalization.html 🤷 

don't feel like i have the capacity to look at this in more detail in the near future, so i am in favor of merging this as is.

**Comment by crlf0710** [comment]
@spastorino I don't think i'm able to apply some in-depth editing to the text, but i added the `FIXME` note as suggested.

**Review by spastorino — APPROVED** [review]

**Pull request merged**
