### PR TITLE
Fix BodyId link typo in glossary

### PR DESCRIPTION
**Pull request by Nashenas88**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Hmmm... CI failing on something unrelated to your changes here Paul.  

https://travis-ci.com/github/rust-lang/rustc-dev-guide/builds/167907317#L338

@mark-i-m OK to merge with this fail?

**Comment by Nashenas88** [comment]
@chrissimpkins I fixed the broken link in this case as well. Seems the enum was split into an enum kind and a wrapping struct. I pointed to the struct for now since it seems to be the main point of use.

**Comment by LeSeulArtichaut** [comment]
I opened #711 to fix the broken link (I didn't see it was fixed here).

**Comment by LeSeulArtichaut** [comment]
> @mark-i-m OK to merge with this fail?

Btw @chrissimpkins I think we can't merge when CI fails because it is marked as "required".

**Pull request merged**
