### PR TITLE
Overview updates: parser

### PR DESCRIPTION
**Pull request by chrissimpkins**
Do not merge into master.

Working branch for the Overview document in #633

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@rust-lang/wg-rustc-dev-guide  The detailed outline for the rustc_interface, lexer, and parser are ready for review as of https://github.com/rust-lang/rustc-dev-guide/pull/669/commits/b3e75e8b7b32c71e7d97f2e98a262ea279cfed27.

**Comment by chrissimpkins** [comment]
No problem at all.  I have a good outline now and can move it out of the outline to start making sections in the chapter.  What do you feel we should leave in the outline? One line summary and entry point?

**Comment by mark-i-m** [comment]
@chrissimpkins I posted on zulip. I would really want to see what others in the WG think and try to come a consensus about how much detail to have in the overview.

**Comment by chrissimpkins** [comment]
Sounds good.  Won’t remove anything here yet.

**Comment by mark-i-m** [comment]
rebased

**Comment by mark-i-m** [comment]
Merged into #633

**Pull request closed without merging**
