### PR TITLE
Fix rebase

### PR DESCRIPTION
**Pull request by mark-i-m**
Blocked on #757 

Redo of #737 but correct (I hope)

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
#757 was merged, marking as unblocked.

**Comment by mark-i-m** [comment]
(CI failure is unrelated: https://linker.iecc.com/ appears to be down atm)

**Comment by mark-i-m** [comment]
Aha! It works. This PR is behind master, and CI just passed when I reran without rebasing :tada:

**Comment by mark-i-m** [comment]
I think so :fingers_crossed:

**Pull request merged**
