### PR TITLE
Move date-check comment to fix Markdown syntax

### PR DESCRIPTION
**Pull request by camelid**
The inline code wasn't being rendered correctly.

### CODE REVIEW

**Comment by jyn514** [comment]
I don't understand - why didn't it work before? Why does this change fix it?

**Comment by camelid** [comment]
Quirks of Markdown–HTML interaction: https://github.com/rust-lang/rustc-dev-guide/pull/1067#discussion_r579744499

**Review by jyn514 — APPROVED** [review]
Hmm, ok - can you file a bug upstream with pulldown?

**Comment by camelid** [comment]
> Hmm, ok - can you file a bug upstream with pulldown?

Given that GitHub also renders it weirdly, it may not be a bug.

**Pull request merged**
